spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:C:\usr\spring\db'
  jpa:
    hibernate:
      ddl-auto: update
my.prop: 'test'
task.allowMultipleTasksFromTemplate: false
